# Generates javadoc for core + all bindings and uploads it to S3.
# The resulting javadoc is available at https://javadoc.lwjgl.org/
name: LWJGL Javadoc generation

on:
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  S3_PARAMS: --cache-control "public,must-revalidate,proxy-revalidate,max-age=0"
  ANT_OPTS: -Xmx2G
  LWJGL_BUILD_TYPE: nightly

jobs:
  linux:
    name: Javadoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - run: |
          git clone https://github.com/LWJGL-CI/OculusSDK.git ../OculusSDK
          curl https://cdn.azul.com/zulu/bin/zulu8.64.0.19-ca-fx-jdk8.0.345-linux_x64.tar.gz --output jdk8.tar.gz
          curl https://cdn.azul.com/zulu/bin/zulu19.28.81-ca-jdk19.0.0-linux_x64.tar.gz --output jdk19.tar.gz
          mkdir jdk8
          mkdir jdk19
          tar xf jdk8.tar.gz -C jdk8 --strip-components 1
          tar xf jdk19.tar.gz -C jdk19 --strip-components 1
        name: Install dependencies
      - run: JAVA_HOME=$(pwd)/jdk8 ant -emacs hydrate-kotlinc clean-generated generate
        name: Generate bindings
      - run: JAVA_HOME=$(pwd)/jdk8 ant -emacs compile
        name: Build Java
      - run: JAVA8_HOME=$(pwd)/jdk8 JAVA_HOME=$(pwd)/jdk19 ANT_OPTS="$ANT_OPTS -Djava.security.manager=allow" ant -emacs javadoc
        name: Generate javadoc
      - run: aws s3 sync bin/javadoc s3://lwjgl-javadoc/ --delete
        name: Upload javadoc to S3